version: "3.8"

services:

  mongodb:
    image: mongo:6
    container_name: mongo-data
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    image: kube-backend
    container_name: minikube-backend
    ports:
      - "3500:3500"
    environment:
      - MONGO_CONN_STR=mongodb://mongodb:27017/tasksdb
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    image: kube-frontend
    container_name: minikube-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data: