apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: os-namespace
spec:
  selector:
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP